// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: backward_compat.proto

package generated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// NoAnnotationsServiceClient is the client API for NoAnnotationsService service.
type NoAnnotationsServiceClient interface {
	SimpleAction(ctx context.Context, req *SimpleRequest, opts ...NoAnnotationsServiceCallOption) (*SimpleResponse, error)
	AnotherAction(ctx context.Context, req *AnotherRequest, opts ...NoAnnotationsServiceCallOption) (*AnotherResponse, error)
}

// noAnnotationsServiceClient is the implementation of NoAnnotationsServiceClient.
type noAnnotationsServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ NoAnnotationsServiceClient = (*noAnnotationsServiceClient)(nil)

// NoAnnotationsServiceClientOption configures a NoAnnotationsService client.
type NoAnnotationsServiceClientOption func(*noAnnotationsServiceClient)

// WithNoAnnotationsServiceHTTPClient sets the HTTP client to use for requests.
func WithNoAnnotationsServiceHTTPClient(client *http.Client) NoAnnotationsServiceClientOption {
	return func(c *noAnnotationsServiceClient) {
		c.httpClient = client
	}
}

// WithNoAnnotationsServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithNoAnnotationsServiceContentType(contentType string) NoAnnotationsServiceClientOption {
	return func(c *noAnnotationsServiceClient) {
		c.contentType = contentType
	}
}

// WithNoAnnotationsServiceDefaultHeader sets a default header to include in all requests.
func WithNoAnnotationsServiceDefaultHeader(key, value string) NoAnnotationsServiceClientOption {
	return func(c *noAnnotationsServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithNoAnnotationsServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithNoAnnotationsServiceDiscardUnknownFields(discard bool) NoAnnotationsServiceClientOption {
	return func(c *noAnnotationsServiceClient) {
		c.discardUnknownFields = discard
	}
}

// NoAnnotationsServiceCallOption configures a single RPC call.
type NoAnnotationsServiceCallOption func(*noAnnotationsServiceCallOptions)

// noAnnotationsServiceCallOptions holds options for a single RPC call.
type noAnnotationsServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithNoAnnotationsServiceHeader adds a header to a single request.
func WithNoAnnotationsServiceHeader(key, value string) NoAnnotationsServiceCallOption {
	return func(o *noAnnotationsServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithNoAnnotationsServiceCallContentType sets the content type for a single request.
func WithNoAnnotationsServiceCallContentType(contentType string) NoAnnotationsServiceCallOption {
	return func(o *noAnnotationsServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithNoAnnotationsServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithNoAnnotationsServiceDiscardUnknownFields.
func WithNoAnnotationsServiceCallDiscardUnknownFields(discard bool) NoAnnotationsServiceCallOption {
	return func(o *noAnnotationsServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewNoAnnotationsServiceClient creates a new NoAnnotationsService client.
func NewNoAnnotationsServiceClient(baseURL string, opts ...NoAnnotationsServiceClientOption) NoAnnotationsServiceClient {
	c := &noAnnotationsServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// SimpleAction calls the SimpleAction RPC.
func (c *noAnnotationsServiceClient) SimpleAction(ctx context.Context, req *SimpleRequest, opts ...NoAnnotationsServiceCallOption) (*SimpleResponse, error) {
	callOpts := &noAnnotationsServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/simpleAction"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &SimpleResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// AnotherAction calls the AnotherAction RPC.
func (c *noAnnotationsServiceClient) AnotherAction(ctx context.Context, req *AnotherRequest, opts ...NoAnnotationsServiceCallOption) (*AnotherResponse, error) {
	callOpts := &noAnnotationsServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/anotherAction"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &AnotherResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *noAnnotationsServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *noAnnotationsServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *noAnnotationsServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}

// BasePathOnlyServiceClient is the client API for BasePathOnlyService service.
type BasePathOnlyServiceClient interface {
	ActionOne(ctx context.Context, req *ActionRequest, opts ...BasePathOnlyServiceCallOption) (*ActionResponse, error)
	ActionTwo(ctx context.Context, req *ActionRequest, opts ...BasePathOnlyServiceCallOption) (*ActionResponse, error)
}

// basePathOnlyServiceClient is the implementation of BasePathOnlyServiceClient.
type basePathOnlyServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ BasePathOnlyServiceClient = (*basePathOnlyServiceClient)(nil)

// BasePathOnlyServiceClientOption configures a BasePathOnlyService client.
type BasePathOnlyServiceClientOption func(*basePathOnlyServiceClient)

// WithBasePathOnlyServiceHTTPClient sets the HTTP client to use for requests.
func WithBasePathOnlyServiceHTTPClient(client *http.Client) BasePathOnlyServiceClientOption {
	return func(c *basePathOnlyServiceClient) {
		c.httpClient = client
	}
}

// WithBasePathOnlyServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithBasePathOnlyServiceContentType(contentType string) BasePathOnlyServiceClientOption {
	return func(c *basePathOnlyServiceClient) {
		c.contentType = contentType
	}
}

// WithBasePathOnlyServiceDefaultHeader sets a default header to include in all requests.
func WithBasePathOnlyServiceDefaultHeader(key, value string) BasePathOnlyServiceClientOption {
	return func(c *basePathOnlyServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithBasePathOnlyServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithBasePathOnlyServiceDiscardUnknownFields(discard bool) BasePathOnlyServiceClientOption {
	return func(c *basePathOnlyServiceClient) {
		c.discardUnknownFields = discard
	}
}

// BasePathOnlyServiceCallOption configures a single RPC call.
type BasePathOnlyServiceCallOption func(*basePathOnlyServiceCallOptions)

// basePathOnlyServiceCallOptions holds options for a single RPC call.
type basePathOnlyServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithBasePathOnlyServiceHeader adds a header to a single request.
func WithBasePathOnlyServiceHeader(key, value string) BasePathOnlyServiceCallOption {
	return func(o *basePathOnlyServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithBasePathOnlyServiceCallContentType sets the content type for a single request.
func WithBasePathOnlyServiceCallContentType(contentType string) BasePathOnlyServiceCallOption {
	return func(o *basePathOnlyServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithBasePathOnlyServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithBasePathOnlyServiceDiscardUnknownFields.
func WithBasePathOnlyServiceCallDiscardUnknownFields(discard bool) BasePathOnlyServiceCallOption {
	return func(o *basePathOnlyServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewBasePathOnlyServiceClient creates a new BasePathOnlyService client.
func NewBasePathOnlyServiceClient(baseURL string, opts ...BasePathOnlyServiceClientOption) BasePathOnlyServiceClient {
	c := &basePathOnlyServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// ActionOne calls the ActionOne RPC.
func (c *basePathOnlyServiceClient) ActionOne(ctx context.Context, req *ActionRequest, opts ...BasePathOnlyServiceCallOption) (*ActionResponse, error) {
	callOpts := &basePathOnlyServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v2/actionOne"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &ActionResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ActionTwo calls the ActionTwo RPC.
func (c *basePathOnlyServiceClient) ActionTwo(ctx context.Context, req *ActionRequest, opts ...BasePathOnlyServiceCallOption) (*ActionResponse, error) {
	callOpts := &basePathOnlyServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v2/actionTwo"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &ActionResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *basePathOnlyServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *basePathOnlyServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *basePathOnlyServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
