// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: bytes_encoding.proto

package bytesencoding

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// BytesEncodingServiceClient is the client API for BytesEncodingService service.
type BytesEncodingServiceClient interface {
	TestBytesEncoding(ctx context.Context, req *BytesEncodingTest, opts ...BytesEncodingServiceCallOption) (*BytesEncodingTest, error)
	GetBytesEncoding(ctx context.Context, req *BytesEncodingRequest, opts ...BytesEncodingServiceCallOption) (*BytesEncodingTest, error)
}

// bytesEncodingServiceClient is the implementation of BytesEncodingServiceClient.
type bytesEncodingServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ BytesEncodingServiceClient = (*bytesEncodingServiceClient)(nil)

// BytesEncodingServiceClientOption configures a BytesEncodingService client.
type BytesEncodingServiceClientOption func(*bytesEncodingServiceClient)

// WithBytesEncodingServiceHTTPClient sets the HTTP client to use for requests.
func WithBytesEncodingServiceHTTPClient(client *http.Client) BytesEncodingServiceClientOption {
	return func(c *bytesEncodingServiceClient) {
		c.httpClient = client
	}
}

// WithBytesEncodingServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithBytesEncodingServiceContentType(contentType string) BytesEncodingServiceClientOption {
	return func(c *bytesEncodingServiceClient) {
		c.contentType = contentType
	}
}

// WithBytesEncodingServiceDefaultHeader sets a default header to include in all requests.
func WithBytesEncodingServiceDefaultHeader(key, value string) BytesEncodingServiceClientOption {
	return func(c *bytesEncodingServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithBytesEncodingServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithBytesEncodingServiceDiscardUnknownFields(discard bool) BytesEncodingServiceClientOption {
	return func(c *bytesEncodingServiceClient) {
		c.discardUnknownFields = discard
	}
}

// BytesEncodingServiceCallOption configures a single RPC call.
type BytesEncodingServiceCallOption func(*bytesEncodingServiceCallOptions)

// bytesEncodingServiceCallOptions holds options for a single RPC call.
type bytesEncodingServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithBytesEncodingServiceHeader adds a header to a single request.
func WithBytesEncodingServiceHeader(key, value string) BytesEncodingServiceCallOption {
	return func(o *bytesEncodingServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithBytesEncodingServiceCallContentType sets the content type for a single request.
func WithBytesEncodingServiceCallContentType(contentType string) BytesEncodingServiceCallOption {
	return func(o *bytesEncodingServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithBytesEncodingServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithBytesEncodingServiceDiscardUnknownFields.
func WithBytesEncodingServiceCallDiscardUnknownFields(discard bool) BytesEncodingServiceCallOption {
	return func(o *bytesEncodingServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewBytesEncodingServiceClient creates a new BytesEncodingService client.
func NewBytesEncodingServiceClient(baseURL string, opts ...BytesEncodingServiceClientOption) BytesEncodingServiceClient {
	c := &bytesEncodingServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// TestBytesEncoding calls the TestBytesEncoding RPC.
func (c *bytesEncodingServiceClient) TestBytesEncoding(ctx context.Context, req *BytesEncodingTest, opts ...BytesEncodingServiceCallOption) (*BytesEncodingTest, error) {
	callOpts := &bytesEncodingServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/bytes-encoding"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &BytesEncodingTest{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetBytesEncoding calls the GetBytesEncoding RPC.
func (c *bytesEncodingServiceClient) GetBytesEncoding(ctx context.Context, req *BytesEncodingRequest, opts ...BytesEncodingServiceCallOption) (*BytesEncodingTest, error) {
	callOpts := &bytesEncodingServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/bytes-encoding/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &BytesEncodingTest{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *bytesEncodingServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *bytesEncodingServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *bytesEncodingServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
