// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: empty_behavior.proto

package emptybehavior

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// EmptyBehaviorServiceClient is the client API for EmptyBehaviorService service.
type EmptyBehaviorServiceClient interface {
	GetResponse(ctx context.Context, req *GetResponseRequest, opts ...EmptyBehaviorServiceCallOption) (*Response, error)
}

// emptyBehaviorServiceClient is the implementation of EmptyBehaviorServiceClient.
type emptyBehaviorServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ EmptyBehaviorServiceClient = (*emptyBehaviorServiceClient)(nil)

// EmptyBehaviorServiceClientOption configures a EmptyBehaviorService client.
type EmptyBehaviorServiceClientOption func(*emptyBehaviorServiceClient)

// WithEmptyBehaviorServiceHTTPClient sets the HTTP client to use for requests.
func WithEmptyBehaviorServiceHTTPClient(client *http.Client) EmptyBehaviorServiceClientOption {
	return func(c *emptyBehaviorServiceClient) {
		c.httpClient = client
	}
}

// WithEmptyBehaviorServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithEmptyBehaviorServiceContentType(contentType string) EmptyBehaviorServiceClientOption {
	return func(c *emptyBehaviorServiceClient) {
		c.contentType = contentType
	}
}

// WithEmptyBehaviorServiceDefaultHeader sets a default header to include in all requests.
func WithEmptyBehaviorServiceDefaultHeader(key, value string) EmptyBehaviorServiceClientOption {
	return func(c *emptyBehaviorServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithEmptyBehaviorServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithEmptyBehaviorServiceDiscardUnknownFields(discard bool) EmptyBehaviorServiceClientOption {
	return func(c *emptyBehaviorServiceClient) {
		c.discardUnknownFields = discard
	}
}

// EmptyBehaviorServiceCallOption configures a single RPC call.
type EmptyBehaviorServiceCallOption func(*emptyBehaviorServiceCallOptions)

// emptyBehaviorServiceCallOptions holds options for a single RPC call.
type emptyBehaviorServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithEmptyBehaviorServiceHeader adds a header to a single request.
func WithEmptyBehaviorServiceHeader(key, value string) EmptyBehaviorServiceCallOption {
	return func(o *emptyBehaviorServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithEmptyBehaviorServiceCallContentType sets the content type for a single request.
func WithEmptyBehaviorServiceCallContentType(contentType string) EmptyBehaviorServiceCallOption {
	return func(o *emptyBehaviorServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithEmptyBehaviorServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithEmptyBehaviorServiceDiscardUnknownFields.
func WithEmptyBehaviorServiceCallDiscardUnknownFields(discard bool) EmptyBehaviorServiceCallOption {
	return func(o *emptyBehaviorServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewEmptyBehaviorServiceClient creates a new EmptyBehaviorService client.
func NewEmptyBehaviorServiceClient(baseURL string, opts ...EmptyBehaviorServiceClientOption) EmptyBehaviorServiceClient {
	c := &emptyBehaviorServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// GetResponse calls the GetResponse RPC.
func (c *emptyBehaviorServiceClient) GetResponse(ctx context.Context, req *GetResponseRequest, opts ...EmptyBehaviorServiceCallOption) (*Response, error) {
	callOpts := &emptyBehaviorServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/responses/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Response{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *emptyBehaviorServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *emptyBehaviorServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *emptyBehaviorServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
