// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: enum_encoding.proto

package enumencoding

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// EnumEncodingServiceClient is the client API for EnumEncodingService service.
type EnumEncodingServiceClient interface {
	GetEnumTest(ctx context.Context, req *GetEnumTestRequest, opts ...EnumEncodingServiceCallOption) (*EnumEncodingTest, error)
}

// enumEncodingServiceClient is the implementation of EnumEncodingServiceClient.
type enumEncodingServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ EnumEncodingServiceClient = (*enumEncodingServiceClient)(nil)

// EnumEncodingServiceClientOption configures a EnumEncodingService client.
type EnumEncodingServiceClientOption func(*enumEncodingServiceClient)

// WithEnumEncodingServiceHTTPClient sets the HTTP client to use for requests.
func WithEnumEncodingServiceHTTPClient(client *http.Client) EnumEncodingServiceClientOption {
	return func(c *enumEncodingServiceClient) {
		c.httpClient = client
	}
}

// WithEnumEncodingServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithEnumEncodingServiceContentType(contentType string) EnumEncodingServiceClientOption {
	return func(c *enumEncodingServiceClient) {
		c.contentType = contentType
	}
}

// WithEnumEncodingServiceDefaultHeader sets a default header to include in all requests.
func WithEnumEncodingServiceDefaultHeader(key, value string) EnumEncodingServiceClientOption {
	return func(c *enumEncodingServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithEnumEncodingServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithEnumEncodingServiceDiscardUnknownFields(discard bool) EnumEncodingServiceClientOption {
	return func(c *enumEncodingServiceClient) {
		c.discardUnknownFields = discard
	}
}

// EnumEncodingServiceCallOption configures a single RPC call.
type EnumEncodingServiceCallOption func(*enumEncodingServiceCallOptions)

// enumEncodingServiceCallOptions holds options for a single RPC call.
type enumEncodingServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithEnumEncodingServiceHeader adds a header to a single request.
func WithEnumEncodingServiceHeader(key, value string) EnumEncodingServiceCallOption {
	return func(o *enumEncodingServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithEnumEncodingServiceCallContentType sets the content type for a single request.
func WithEnumEncodingServiceCallContentType(contentType string) EnumEncodingServiceCallOption {
	return func(o *enumEncodingServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithEnumEncodingServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithEnumEncodingServiceDiscardUnknownFields.
func WithEnumEncodingServiceCallDiscardUnknownFields(discard bool) EnumEncodingServiceCallOption {
	return func(o *enumEncodingServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewEnumEncodingServiceClient creates a new EnumEncodingService client.
func NewEnumEncodingServiceClient(baseURL string, opts ...EnumEncodingServiceClientOption) EnumEncodingServiceClient {
	c := &enumEncodingServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// GetEnumTest calls the GetEnumTest RPC.
func (c *enumEncodingServiceClient) GetEnumTest(ctx context.Context, req *GetEnumTestRequest, opts ...EnumEncodingServiceCallOption) (*EnumEncodingTest, error) {
	callOpts := &enumEncodingServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/test/enum/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &EnumEncodingTest{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *enumEncodingServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *enumEncodingServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *enumEncodingServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
