// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: int64_nested_encoding.proto

package int64nestedencoding

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// SensorServiceClient is the client API for SensorService service.
type SensorServiceClient interface {
	GetSensorReading(ctx context.Context, req *GetSensorRequest, opts ...SensorServiceCallOption) (*GetSensorReadingResponse, error)
	GetMultiSensor(ctx context.Context, req *GetSensorRequest, opts ...SensorServiceCallOption) (*GetMultiSensorResponse, error)
}

// sensorServiceClient is the implementation of SensorServiceClient.
type sensorServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ SensorServiceClient = (*sensorServiceClient)(nil)

// SensorServiceClientOption configures a SensorService client.
type SensorServiceClientOption func(*sensorServiceClient)

// WithSensorServiceHTTPClient sets the HTTP client to use for requests.
func WithSensorServiceHTTPClient(client *http.Client) SensorServiceClientOption {
	return func(c *sensorServiceClient) {
		c.httpClient = client
	}
}

// WithSensorServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithSensorServiceContentType(contentType string) SensorServiceClientOption {
	return func(c *sensorServiceClient) {
		c.contentType = contentType
	}
}

// WithSensorServiceDefaultHeader sets a default header to include in all requests.
func WithSensorServiceDefaultHeader(key, value string) SensorServiceClientOption {
	return func(c *sensorServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithSensorServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithSensorServiceDiscardUnknownFields(discard bool) SensorServiceClientOption {
	return func(c *sensorServiceClient) {
		c.discardUnknownFields = discard
	}
}

// SensorServiceCallOption configures a single RPC call.
type SensorServiceCallOption func(*sensorServiceCallOptions)

// sensorServiceCallOptions holds options for a single RPC call.
type sensorServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithSensorServiceHeader adds a header to a single request.
func WithSensorServiceHeader(key, value string) SensorServiceCallOption {
	return func(o *sensorServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithSensorServiceCallContentType sets the content type for a single request.
func WithSensorServiceCallContentType(contentType string) SensorServiceCallOption {
	return func(o *sensorServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithSensorServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithSensorServiceDiscardUnknownFields.
func WithSensorServiceCallDiscardUnknownFields(discard bool) SensorServiceCallOption {
	return func(o *sensorServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewSensorServiceClient creates a new SensorService client.
func NewSensorServiceClient(baseURL string, opts ...SensorServiceClientOption) SensorServiceClient {
	c := &sensorServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// GetSensorReading calls the GetSensorReading RPC.
func (c *sensorServiceClient) GetSensorReading(ctx context.Context, req *GetSensorRequest, opts ...SensorServiceCallOption) (*GetSensorReadingResponse, error) {
	callOpts := &sensorServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/sensors/{sensor_id}"
	path = strings.Replace(path, "{sensor_id}", url.PathEscape(fmt.Sprint(req.SensorId)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &GetSensorReadingResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetMultiSensor calls the GetMultiSensor RPC.
func (c *sensorServiceClient) GetMultiSensor(ctx context.Context, req *GetSensorRequest, opts ...SensorServiceCallOption) (*GetMultiSensorResponse, error) {
	callOpts := &sensorServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/sensors/{sensor_id}/multi"
	path = strings.Replace(path, "{sensor_id}", url.PathEscape(fmt.Sprint(req.SensorId)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &GetMultiSensorResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *sensorServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *sensorServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *sensorServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
