// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: int64_nested_encoding.proto

package int64nestedencoding

import (
	"encoding/json"
	"strconv"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON implements json.Marshaler for SensorReading.
// This method handles int64_encoding=NUMBER fields: timestamp_ms, values
// Warning: int64 fields with NUMBER encoding may lose precision for values > 2^53 in JavaScript.
func (x *SensorReading) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to modify NUMBER-encoded int64 fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert TimestampMs from string to number
	if x.TimestampMs != 0 {
		raw["timestampMs"], _ = json.Marshal(x.TimestampMs)
	} else {
		// Remove the field if zero (proto3 default behavior)
		delete(raw, "timestampMs")
	}

	// Convert repeated Values from strings to numbers
	if len(x.Values) > 0 {
		raw["values"], _ = json.Marshal(x.Values)
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for SensorReading.
// This method handles int64_encoding=NUMBER fields: timestamp_ms, values
func (x *SensorReading) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *SensorReading) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// First, parse the raw JSON to extract NUMBER-encoded fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert timestampMs from number to string for protojson
	if rawVal, ok := raw["timestampMs"]; ok {
		var num int64
		if err := json.Unmarshal(rawVal, &num); err == nil {
			raw["timestampMs"], _ = json.Marshal(strconv.FormatInt(num, 10))
		}
	}

	// Convert repeated values from numbers to strings for protojson
	if rawVal, ok := raw["values"]; ok {
		var nums []int64
		if err := json.Unmarshal(rawVal, &nums); err == nil {
			strs := make([]string, len(nums))
			for i, n := range nums {
				strs[i] = strconv.FormatInt(n, 10)
			}
			raw["values"], _ = json.Marshal(strs)
		}
	}

	// Re-marshal to JSON with string values for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}

// MarshalJSON implements json.Marshaler for GetSensorReadingResponse.
// This method re-marshals nested messages that have int64_encoding=NUMBER fields: reading
func (x *GetSensorReadingResponse) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to re-serialize nested messages with custom MarshalJSON
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize "reading" using its custom MarshalJSON
	if x.Reading != nil {
		raw["reading"], err = json.Marshal(x.Reading)
		if err != nil {
			return nil, err
		}
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for GetSensorReadingResponse.
// This method handles nested messages that have int64_encoding=NUMBER fields: reading
func (x *GetSensorReadingResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *GetSensorReadingResponse) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "reading" using its custom UnmarshalJSON
	if rawVal, ok := raw["reading"]; ok {
		inner := &SensorReading{}
		if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, err := protojson.Marshal(inner)
		if err != nil {
			return err
		}
		raw["reading"] = innerJSON
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}

// MarshalJSON implements json.Marshaler for GetMultiSensorResponse.
// This method re-marshals nested messages that have int64_encoding=NUMBER fields: primary, secondary
func (x *GetMultiSensorResponse) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to re-serialize nested messages with custom MarshalJSON
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize "primary" using its custom MarshalJSON
	if x.Primary != nil {
		raw["primary"], err = json.Marshal(x.Primary)
		if err != nil {
			return nil, err
		}
	}

	// Re-serialize "secondary" using its custom MarshalJSON
	if x.Secondary != nil {
		raw["secondary"], err = json.Marshal(x.Secondary)
		if err != nil {
			return nil, err
		}
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for GetMultiSensorResponse.
// This method handles nested messages that have int64_encoding=NUMBER fields: primary, secondary
func (x *GetMultiSensorResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *GetMultiSensorResponse) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "primary" using its custom UnmarshalJSON
	if rawVal, ok := raw["primary"]; ok {
		inner := &SensorReading{}
		if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, err := protojson.Marshal(inner)
		if err != nil {
			return err
		}
		raw["primary"] = innerJSON
	}

	// Handle "secondary" using its custom UnmarshalJSON
	if rawVal, ok := raw["secondary"]; ok {
		inner := &SensorReading{}
		if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, err := protojson.Marshal(inner)
		if err != nil {
			return err
		}
		raw["secondary"] = innerJSON
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}
