// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: int64_encoding.proto

package int64encoding

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// Int64EncodingServiceClient is the client API for Int64EncodingService service.
type Int64EncodingServiceClient interface {
	GetInt64Test(ctx context.Context, req *GetInt64TestRequest, opts ...Int64EncodingServiceCallOption) (*Int64EncodingTest, error)
}

// int64EncodingServiceClient is the implementation of Int64EncodingServiceClient.
type int64EncodingServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ Int64EncodingServiceClient = (*int64EncodingServiceClient)(nil)

// Int64EncodingServiceClientOption configures a Int64EncodingService client.
type Int64EncodingServiceClientOption func(*int64EncodingServiceClient)

// WithInt64EncodingServiceHTTPClient sets the HTTP client to use for requests.
func WithInt64EncodingServiceHTTPClient(client *http.Client) Int64EncodingServiceClientOption {
	return func(c *int64EncodingServiceClient) {
		c.httpClient = client
	}
}

// WithInt64EncodingServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithInt64EncodingServiceContentType(contentType string) Int64EncodingServiceClientOption {
	return func(c *int64EncodingServiceClient) {
		c.contentType = contentType
	}
}

// WithInt64EncodingServiceDefaultHeader sets a default header to include in all requests.
func WithInt64EncodingServiceDefaultHeader(key, value string) Int64EncodingServiceClientOption {
	return func(c *int64EncodingServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithInt64EncodingServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithInt64EncodingServiceDiscardUnknownFields(discard bool) Int64EncodingServiceClientOption {
	return func(c *int64EncodingServiceClient) {
		c.discardUnknownFields = discard
	}
}

// Int64EncodingServiceCallOption configures a single RPC call.
type Int64EncodingServiceCallOption func(*int64EncodingServiceCallOptions)

// int64EncodingServiceCallOptions holds options for a single RPC call.
type int64EncodingServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithInt64EncodingServiceHeader adds a header to a single request.
func WithInt64EncodingServiceHeader(key, value string) Int64EncodingServiceCallOption {
	return func(o *int64EncodingServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithInt64EncodingServiceCallContentType sets the content type for a single request.
func WithInt64EncodingServiceCallContentType(contentType string) Int64EncodingServiceCallOption {
	return func(o *int64EncodingServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithInt64EncodingServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithInt64EncodingServiceDiscardUnknownFields.
func WithInt64EncodingServiceCallDiscardUnknownFields(discard bool) Int64EncodingServiceCallOption {
	return func(o *int64EncodingServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewInt64EncodingServiceClient creates a new Int64EncodingService client.
func NewInt64EncodingServiceClient(baseURL string, opts ...Int64EncodingServiceClientOption) Int64EncodingServiceClient {
	c := &int64EncodingServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// GetInt64Test calls the GetInt64Test RPC.
func (c *int64EncodingServiceClient) GetInt64Test(ctx context.Context, req *GetInt64TestRequest, opts ...Int64EncodingServiceCallOption) (*Int64EncodingTest, error) {
	callOpts := &int64EncodingServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/test/int64/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Int64EncodingTest{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *int64EncodingServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *int64EncodingServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *int64EncodingServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
