// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: oneof_discriminator.proto

package oneofdiscriminator

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// OneofDiscriminatorServiceClient is the client API for OneofDiscriminatorService service.
type OneofDiscriminatorServiceClient interface {
	TestFlattenedEvent(ctx context.Context, req *FlattenedEvent, opts ...OneofDiscriminatorServiceCallOption) (*FlattenedEvent, error)
	TestNestedEvent(ctx context.Context, req *NestedEvent, opts ...OneofDiscriminatorServiceCallOption) (*NestedEvent, error)
	TestPlainEvent(ctx context.Context, req *PlainEvent, opts ...OneofDiscriminatorServiceCallOption) (*PlainEvent, error)
}

// oneofDiscriminatorServiceClient is the implementation of OneofDiscriminatorServiceClient.
type oneofDiscriminatorServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ OneofDiscriminatorServiceClient = (*oneofDiscriminatorServiceClient)(nil)

// OneofDiscriminatorServiceClientOption configures a OneofDiscriminatorService client.
type OneofDiscriminatorServiceClientOption func(*oneofDiscriminatorServiceClient)

// WithOneofDiscriminatorServiceHTTPClient sets the HTTP client to use for requests.
func WithOneofDiscriminatorServiceHTTPClient(client *http.Client) OneofDiscriminatorServiceClientOption {
	return func(c *oneofDiscriminatorServiceClient) {
		c.httpClient = client
	}
}

// WithOneofDiscriminatorServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithOneofDiscriminatorServiceContentType(contentType string) OneofDiscriminatorServiceClientOption {
	return func(c *oneofDiscriminatorServiceClient) {
		c.contentType = contentType
	}
}

// WithOneofDiscriminatorServiceDefaultHeader sets a default header to include in all requests.
func WithOneofDiscriminatorServiceDefaultHeader(key, value string) OneofDiscriminatorServiceClientOption {
	return func(c *oneofDiscriminatorServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithOneofDiscriminatorServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithOneofDiscriminatorServiceDiscardUnknownFields(discard bool) OneofDiscriminatorServiceClientOption {
	return func(c *oneofDiscriminatorServiceClient) {
		c.discardUnknownFields = discard
	}
}

// OneofDiscriminatorServiceCallOption configures a single RPC call.
type OneofDiscriminatorServiceCallOption func(*oneofDiscriminatorServiceCallOptions)

// oneofDiscriminatorServiceCallOptions holds options for a single RPC call.
type oneofDiscriminatorServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithOneofDiscriminatorServiceHeader adds a header to a single request.
func WithOneofDiscriminatorServiceHeader(key, value string) OneofDiscriminatorServiceCallOption {
	return func(o *oneofDiscriminatorServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithOneofDiscriminatorServiceCallContentType sets the content type for a single request.
func WithOneofDiscriminatorServiceCallContentType(contentType string) OneofDiscriminatorServiceCallOption {
	return func(o *oneofDiscriminatorServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithOneofDiscriminatorServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithOneofDiscriminatorServiceDiscardUnknownFields.
func WithOneofDiscriminatorServiceCallDiscardUnknownFields(discard bool) OneofDiscriminatorServiceCallOption {
	return func(o *oneofDiscriminatorServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewOneofDiscriminatorServiceClient creates a new OneofDiscriminatorService client.
func NewOneofDiscriminatorServiceClient(baseURL string, opts ...OneofDiscriminatorServiceClientOption) OneofDiscriminatorServiceClient {
	c := &oneofDiscriminatorServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// TestFlattenedEvent calls the TestFlattenedEvent RPC.
func (c *oneofDiscriminatorServiceClient) TestFlattenedEvent(ctx context.Context, req *FlattenedEvent, opts ...OneofDiscriminatorServiceCallOption) (*FlattenedEvent, error) {
	callOpts := &oneofDiscriminatorServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/events/flattened"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &FlattenedEvent{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// TestNestedEvent calls the TestNestedEvent RPC.
func (c *oneofDiscriminatorServiceClient) TestNestedEvent(ctx context.Context, req *NestedEvent, opts ...OneofDiscriminatorServiceCallOption) (*NestedEvent, error) {
	callOpts := &oneofDiscriminatorServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/events/nested"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &NestedEvent{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// TestPlainEvent calls the TestPlainEvent RPC.
func (c *oneofDiscriminatorServiceClient) TestPlainEvent(ctx context.Context, req *PlainEvent, opts ...OneofDiscriminatorServiceCallOption) (*PlainEvent, error) {
	callOpts := &oneofDiscriminatorServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/events/plain"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &PlainEvent{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *oneofDiscriminatorServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *oneofDiscriminatorServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *oneofDiscriminatorServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
