// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: sse.proto

package generated

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// SSEServiceClient is the client API for SSEService service.
type SSEServiceClient interface {
	GetStatus(ctx context.Context, req *GetStatusRequest, opts ...SSEServiceCallOption) (*StatusResponse, error)
	StreamEvents(ctx context.Context, req *StreamEventsRequest, opts ...SSEServiceCallOption) (*SSEServiceEventStream[*Event], error)
	StreamResourceEvents(ctx context.Context, req *StreamResourceEventsRequest, opts ...SSEServiceCallOption) (*SSEServiceEventStream[*ResourceEvent], error)
	StreamFilteredEvents(ctx context.Context, req *StreamFilteredEventsRequest, opts ...SSEServiceCallOption) (*SSEServiceEventStream[*Event], error)
}

// sSEServiceClient is the implementation of SSEServiceClient.
type sSEServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ SSEServiceClient = (*sSEServiceClient)(nil)

// SSEServiceClientOption configures a SSEService client.
type SSEServiceClientOption func(*sSEServiceClient)

// WithSSEServiceHTTPClient sets the HTTP client to use for requests.
func WithSSEServiceHTTPClient(client *http.Client) SSEServiceClientOption {
	return func(c *sSEServiceClient) {
		c.httpClient = client
	}
}

// WithSSEServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithSSEServiceContentType(contentType string) SSEServiceClientOption {
	return func(c *sSEServiceClient) {
		c.contentType = contentType
	}
}

// WithSSEServiceDefaultHeader sets a default header to include in all requests.
func WithSSEServiceDefaultHeader(key, value string) SSEServiceClientOption {
	return func(c *sSEServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithSSEServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithSSEServiceDiscardUnknownFields(discard bool) SSEServiceClientOption {
	return func(c *sSEServiceClient) {
		c.discardUnknownFields = discard
	}
}

// SSEServiceCallOption configures a single RPC call.
type SSEServiceCallOption func(*sSEServiceCallOptions)

// sSEServiceCallOptions holds options for a single RPC call.
type sSEServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithSSEServiceHeader adds a header to a single request.
func WithSSEServiceHeader(key, value string) SSEServiceCallOption {
	return func(o *sSEServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithSSEServiceCallContentType sets the content type for a single request.
func WithSSEServiceCallContentType(contentType string) SSEServiceCallOption {
	return func(o *sSEServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithSSEServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithSSEServiceDiscardUnknownFields.
func WithSSEServiceCallDiscardUnknownFields(discard bool) SSEServiceCallOption {
	return func(o *sSEServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewSSEServiceClient creates a new SSEService client.
func NewSSEServiceClient(baseURL string, opts ...SSEServiceClientOption) SSEServiceClient {
	c := &sSEServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// SSEServiceEventStream reads Server-Sent Events from a streaming endpoint.
type SSEServiceEventStream[T proto.Message] struct {
	resp                 *http.Response
	reader               *bufio.Reader
	err                  error
	discardUnknownFields bool
}

// Next reads the next event from the stream.
// Returns false when the stream ends or an error occurs.
func (s *SSEServiceEventStream[T]) Next(event T) bool {
	for {
		line, err := s.reader.ReadString('\n')
		if err != nil {
			if err != io.EOF {
				s.err = err
			}
			return false
		}
		line = strings.TrimRight(line, "\r\n")
		if !strings.HasPrefix(line, "data: ") {
			continue
		}
		data := strings.TrimPrefix(line, "data: ")
		var unmarshalErr error
		if s.discardUnknownFields {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			unmarshalErr = opts.Unmarshal([]byte(data), event)
		} else {
			unmarshalErr = protojson.Unmarshal([]byte(data), event)
		}
		if unmarshalErr != nil {
			s.err = fmt.Errorf("failed to unmarshal SSE event: %w", unmarshalErr)
			return false
		}
		return true
	}
}

// Err returns any error encountered during streaming.
func (s *SSEServiceEventStream[T]) Err() error {
	return s.err
}

// Close closes the underlying HTTP response body.
func (s *SSEServiceEventStream[T]) Close() error {
	return s.resp.Body.Close()
}

// GetStatus calls the GetStatus RPC.
func (c *sSEServiceClient) GetStatus(ctx context.Context, req *GetStatusRequest, opts ...SSEServiceCallOption) (*StatusResponse, error) {
	callOpts := &sSEServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/status"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &StatusResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// StreamEvents calls the StreamEvents SSE streaming RPC.
func (c *sSEServiceClient) StreamEvents(ctx context.Context, req *StreamEventsRequest, opts ...SSEServiceCallOption) (*SSEServiceEventStream[*Event], error) {
	callOpts := &sSEServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/events"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	httpReq.Header.Set("Accept", "text/event-stream")
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		defer resp.Body.Close()
		respBody, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("failed to read error response: %w", readErr)
		}
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	return &SSEServiceEventStream[*Event]{
		resp:                 resp,
		reader:               bufio.NewReader(resp.Body),
		discardUnknownFields: discardUnknown,
	}, nil
}

// StreamResourceEvents calls the StreamResourceEvents SSE streaming RPC.
func (c *sSEServiceClient) StreamResourceEvents(ctx context.Context, req *StreamResourceEventsRequest, opts ...SSEServiceCallOption) (*SSEServiceEventStream[*ResourceEvent], error) {
	callOpts := &sSEServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/resources/{resource_id}/events"
	path = strings.Replace(path, "{resource_id}", url.PathEscape(fmt.Sprint(req.ResourceId)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	httpReq.Header.Set("Accept", "text/event-stream")
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		defer resp.Body.Close()
		respBody, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("failed to read error response: %w", readErr)
		}
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	return &SSEServiceEventStream[*ResourceEvent]{
		resp:                 resp,
		reader:               bufio.NewReader(resp.Body),
		discardUnknownFields: discardUnknown,
	}, nil
}

// StreamFilteredEvents calls the StreamFilteredEvents SSE streaming RPC.
func (c *sSEServiceClient) StreamFilteredEvents(ctx context.Context, req *StreamFilteredEventsRequest, opts ...SSEServiceCallOption) (*SSEServiceEventStream[*Event], error) {
	callOpts := &sSEServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/events/filtered"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.EventType != "" {
		queryParams.Set("type", fmt.Sprint(req.EventType))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	httpReq.Header.Set("Accept", "text/event-stream")
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		defer resp.Body.Close()
		respBody, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("failed to read error response: %w", readErr)
		}
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	return &SSEServiceEventStream[*Event]{
		resp:                 resp,
		reader:               bufio.NewReader(resp.Body),
		discardUnknownFields: discardUnknown,
	}, nil
}

func (c *sSEServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *sSEServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *sSEServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
