// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: timestamp_format.proto

package timestampformat

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// TimestampFormatServiceClient is the client API for TimestampFormatService service.
type TimestampFormatServiceClient interface {
	CreateTimestampFormat(ctx context.Context, req *TimestampFormatTest, opts ...TimestampFormatServiceCallOption) (*TimestampFormatTest, error)
	GetTimestampFormat(ctx context.Context, req *TimestampFormatRequest, opts ...TimestampFormatServiceCallOption) (*TimestampFormatTest, error)
}

// timestampFormatServiceClient is the implementation of TimestampFormatServiceClient.
type timestampFormatServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ TimestampFormatServiceClient = (*timestampFormatServiceClient)(nil)

// TimestampFormatServiceClientOption configures a TimestampFormatService client.
type TimestampFormatServiceClientOption func(*timestampFormatServiceClient)

// WithTimestampFormatServiceHTTPClient sets the HTTP client to use for requests.
func WithTimestampFormatServiceHTTPClient(client *http.Client) TimestampFormatServiceClientOption {
	return func(c *timestampFormatServiceClient) {
		c.httpClient = client
	}
}

// WithTimestampFormatServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithTimestampFormatServiceContentType(contentType string) TimestampFormatServiceClientOption {
	return func(c *timestampFormatServiceClient) {
		c.contentType = contentType
	}
}

// WithTimestampFormatServiceDefaultHeader sets a default header to include in all requests.
func WithTimestampFormatServiceDefaultHeader(key, value string) TimestampFormatServiceClientOption {
	return func(c *timestampFormatServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithTimestampFormatServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithTimestampFormatServiceDiscardUnknownFields(discard bool) TimestampFormatServiceClientOption {
	return func(c *timestampFormatServiceClient) {
		c.discardUnknownFields = discard
	}
}

// TimestampFormatServiceCallOption configures a single RPC call.
type TimestampFormatServiceCallOption func(*timestampFormatServiceCallOptions)

// timestampFormatServiceCallOptions holds options for a single RPC call.
type timestampFormatServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithTimestampFormatServiceHeader adds a header to a single request.
func WithTimestampFormatServiceHeader(key, value string) TimestampFormatServiceCallOption {
	return func(o *timestampFormatServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithTimestampFormatServiceCallContentType sets the content type for a single request.
func WithTimestampFormatServiceCallContentType(contentType string) TimestampFormatServiceCallOption {
	return func(o *timestampFormatServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithTimestampFormatServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithTimestampFormatServiceDiscardUnknownFields.
func WithTimestampFormatServiceCallDiscardUnknownFields(discard bool) TimestampFormatServiceCallOption {
	return func(o *timestampFormatServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewTimestampFormatServiceClient creates a new TimestampFormatService client.
func NewTimestampFormatServiceClient(baseURL string, opts ...TimestampFormatServiceClientOption) TimestampFormatServiceClient {
	c := &timestampFormatServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// CreateTimestampFormat calls the CreateTimestampFormat RPC.
func (c *timestampFormatServiceClient) CreateTimestampFormat(ctx context.Context, req *TimestampFormatTest, opts ...TimestampFormatServiceCallOption) (*TimestampFormatTest, error) {
	callOpts := &timestampFormatServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/timestamp-format"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &TimestampFormatTest{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetTimestampFormat calls the GetTimestampFormat RPC.
func (c *timestampFormatServiceClient) GetTimestampFormat(ctx context.Context, req *TimestampFormatRequest, opts ...TimestampFormatServiceCallOption) (*TimestampFormatTest, error) {
	callOpts := &timestampFormatServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/timestamp-format/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &TimestampFormatTest{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *timestampFormatServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *timestampFormatServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *timestampFormatServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for discard-aware custom unmarshaler first (supports DiscardUnknownFields)
		if unmarshaler, ok := msg.(interface{ UnmarshalJSONWithDiscard([]byte, bool) error }); ok {
			return unmarshaler.UnmarshalJSONWithDiscard(body, discardUnknown)
		}
		// Fall back to standard json.Unmarshaler (e.g. unwrap types)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
