// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: timestamp_format.proto

package timestampformat

import (
	"encoding/json"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON implements json.Marshaler for TimestampFormatTest.
// This method handles timestamp_format fields: unix_seconds_ts, unix_millis_ts, date_ts
func (x *TimestampFormatTest) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to modify timestamp format fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert unix_seconds_ts to TIMESTAMP_FORMAT_UNIX_SECONDS format
	if x.UnixSecondsTs != nil {
		t := x.UnixSecondsTs.AsTime()
		raw["unixSecondsTs"], _ = json.Marshal(t.Unix())
	}

	// Convert unix_millis_ts to TIMESTAMP_FORMAT_UNIX_MILLIS format
	if x.UnixMillisTs != nil {
		t := x.UnixMillisTs.AsTime()
		raw["unixMillisTs"], _ = json.Marshal(t.UnixMilli())
	}

	// Convert date_ts to TIMESTAMP_FORMAT_DATE format
	if x.DateTs != nil {
		t := x.DateTs.AsTime()
		raw["dateTs"], _ = json.Marshal(t.Format("2006-01-02"))
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for TimestampFormatTest.
// This method handles timestamp_format fields: unix_seconds_ts, unix_millis_ts, date_ts
func (x *TimestampFormatTest) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *TimestampFormatTest) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// Parse the raw JSON to extract timestamp format fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert unixSecondsTs from TIMESTAMP_FORMAT_UNIX_SECONDS to RFC 3339 for protojson
	if v, ok := raw["unixSecondsTs"]; ok {
		var n int64
		if err := json.Unmarshal(v, &n); err == nil {
			t := time.Unix(n, 0)
			raw["unixSecondsTs"], _ = json.Marshal(t.Format(time.RFC3339Nano))
		}
	}

	// Convert unixMillisTs from TIMESTAMP_FORMAT_UNIX_MILLIS to RFC 3339 for protojson
	if v, ok := raw["unixMillisTs"]; ok {
		var n int64
		if err := json.Unmarshal(v, &n); err == nil {
			t := time.UnixMilli(n)
			raw["unixMillisTs"], _ = json.Marshal(t.Format(time.RFC3339Nano))
		}
	}

	// Convert dateTs from TIMESTAMP_FORMAT_DATE to RFC 3339 for protojson
	if v, ok := raw["dateTs"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil {
			t, parseErr := time.Parse("2006-01-02", s)
			if parseErr == nil {
				raw["dateTs"], _ = json.Marshal(t.Format(time.RFC3339Nano))
			}
		}
	}

	// Re-marshal with RFC 3339 values for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}
