// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: empty_behavior.proto

package emptybehavior

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// MarshalJSON implements json.Marshaler for Response.
// This method handles empty_behavior fields: metadata_preserve, metadata_null, metadata_omit, settings
func (x *Response) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to handle empty_behavior fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Handle empty_behavior for field: metadata_preserve
	if x.MetadataPreserve != nil && proto.Size(x.MetadataPreserve) == 0 {
		// EMPTY_BEHAVIOR_PRESERVE: keep as {} (default protojson behavior)
		// No action needed - protojson already emits {}
	}

	// Handle empty_behavior for field: metadata_null
	if x.MetadataNull != nil && proto.Size(x.MetadataNull) == 0 {
		// EMPTY_BEHAVIOR_NULL: serialize empty message as null
		raw["metadataNull"] = []byte("null")
	}

	// Handle empty_behavior for field: metadata_omit
	if x.MetadataOmit != nil && proto.Size(x.MetadataOmit) == 0 {
		// EMPTY_BEHAVIOR_OMIT: remove field when message is empty
		delete(raw, "metadataOmit")
	}

	// Handle empty_behavior for field: settings
	if x.Settings != nil && proto.Size(x.Settings) == 0 {
		// EMPTY_BEHAVIOR_NULL: serialize empty message as null
		raw["settings"] = []byte("null")
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for Response.
// This method handles empty_behavior fields: metadata_preserve, metadata_null, metadata_omit, settings
func (x *Response) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *Response) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// Parse to check for explicit null values on empty_behavior=NULL fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle empty_behavior=NULL: convert null to {} for protojson
	if rawVal, ok := raw["metadataNull"]; ok && string(rawVal) == "null" {
		raw["metadataNull"] = []byte("{}")
	}

	// Handle empty_behavior=NULL: convert null to {} for protojson
	if rawVal, ok := raw["settings"]; ok && string(rawVal) == "null" {
		raw["settings"] = []byte("{}")
	}

	// Re-marshal for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}
