// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: int64_repeated_nested_encoding.proto

package int64repeatednested

import (
	"encoding/json"
	"strconv"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON implements json.Marshaler for Stock.
// This method handles int64_encoding=NUMBER fields: volume
// Warning: int64 fields with NUMBER encoding may lose precision for values > 2^53 in JavaScript.
func (x *Stock) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to modify NUMBER-encoded int64 fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert Volume from string to number
	if x.Volume != 0 {
		raw["volume"], _ = json.Marshal(x.Volume)
	} else {
		// Remove the field if zero (proto3 default behavior)
		delete(raw, "volume")
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for Stock.
// This method handles int64_encoding=NUMBER fields: volume
func (x *Stock) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *Stock) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// First, parse the raw JSON to extract NUMBER-encoded fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert volume from number to string for protojson
	if rawVal, ok := raw["volume"]; ok {
		var num int64
		if err := json.Unmarshal(rawVal, &num); err == nil {
			raw["volume"], _ = json.Marshal(strconv.FormatInt(num, 10))
		}
	}

	// Re-marshal to JSON with string values for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}

// MarshalJSON implements json.Marshaler for GetStocksResponse.
// This method re-marshals nested messages that have int64_encoding=NUMBER fields: stocks
func (x *GetStocksResponse) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to re-serialize nested messages with custom MarshalJSON
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "stocks" using its custom MarshalJSON
	if len(x.Stocks) > 0 {
		raw["stocks"], err = json.Marshal(x.Stocks)
		if err != nil {
			return nil, err
		}
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for GetStocksResponse.
// This method handles nested messages that have int64_encoding=NUMBER fields: stocks
func (x *GetStocksResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *GetStocksResponse) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle repeated "stocks" using its custom UnmarshalJSON
	if rawVal, ok := raw["stocks"]; ok {
		var innerList []*Stock
		if err := json.Unmarshal(rawVal, &innerList); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(innerList))
		for i, item := range innerList {
			if item == nil {
				protoItems[i] = json.RawMessage("null")
				continue
			}
			itemJSON, marshalErr := protojson.Marshal(item)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw["stocks"] = protoJSON
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}
