// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: nullable.proto

package nullable

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON implements json.Marshaler for User.
// This method handles nullable fields: middle_name, age, is_verified
func (x *User) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to handle nullable fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Handle nullable field: middle_name
	// proto3 optional + nullable=true: emit null when not set
	if x.MiddleName == nil {
		raw["middleName"] = []byte("null")
	}

	// Handle nullable field: age
	// proto3 optional + nullable=true: emit null when not set
	if x.Age == nil {
		raw["age"] = []byte("null")
	}

	// Handle nullable field: is_verified
	// proto3 optional + nullable=true: emit null when not set
	if x.IsVerified == nil {
		raw["isVerified"] = []byte("null")
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for User.
// This method handles nullable fields: middle_name, age, is_verified
func (x *User) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *User) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// Parse to check for explicit null values on nullable fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle nullable field: middle_name
	// Remove explicit null so protojson leaves field unset
	if rawVal, ok := raw["middleName"]; ok && string(rawVal) == "null" {
		delete(raw, "middleName")
	}

	// Handle nullable field: age
	// Remove explicit null so protojson leaves field unset
	if rawVal, ok := raw["age"]; ok && string(rawVal) == "null" {
		delete(raw, "age")
	}

	// Handle nullable field: is_verified
	// Remove explicit null so protojson leaves field unset
	if rawVal, ok := raw["isVerified"]; ok && string(rawVal) == "null" {
		delete(raw, "isVerified")
	}

	// Re-marshal without nulls for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}
