// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: unwrap_int64_encoding.proto

package unwrapint64encoding

import (
	"encoding/json"
	"strconv"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON implements json.Marshaler for Bar.
// This method handles int64_encoding=NUMBER fields: volume
// Warning: int64 fields with NUMBER encoding may lose precision for values > 2^53 in JavaScript.
func (x *Bar) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to modify NUMBER-encoded int64 fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert Volume from string to number
	if x.Volume != 0 {
		raw["volume"], _ = json.Marshal(x.Volume)
	} else {
		// Remove the field if zero (proto3 default behavior)
		delete(raw, "volume")
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for Bar.
// This method handles int64_encoding=NUMBER fields: volume
func (x *Bar) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *Bar) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// First, parse the raw JSON to extract NUMBER-encoded fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert volume from number to string for protojson
	if rawVal, ok := raw["volume"]; ok {
		var num int64
		if err := json.Unmarshal(rawVal, &num); err == nil {
			raw["volume"], _ = json.Marshal(strconv.FormatInt(num, 10))
		}
	}

	// Re-marshal to JSON with string values for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}

// MarshalJSON implements json.Marshaler for Meta.
// This method handles int64_encoding=NUMBER fields: timestamp
// Warning: int64 fields with NUMBER encoding may lose precision for values > 2^53 in JavaScript.
func (x *Meta) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := protojson.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to modify NUMBER-encoded int64 fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert Timestamp from string to number
	if x.Timestamp != 0 {
		raw["timestamp"], _ = json.Marshal(x.Timestamp)
	} else {
		// Remove the field if zero (proto3 default behavior)
		delete(raw, "timestamp")
	}

	return json.Marshal(raw)
}

// UnmarshalJSON implements json.Unmarshaler for Meta.
// This method handles int64_encoding=NUMBER fields: timestamp
func (x *Meta) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONWithDiscard(data, false)
}

// UnmarshalJSONWithDiscard is like UnmarshalJSON but supports discarding unknown fields.
func (x *Meta) UnmarshalJSONWithDiscard(data []byte, discardUnknown bool) error {
	// First, parse the raw JSON to extract NUMBER-encoded fields
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert timestamp from number to string for protojson
	if rawVal, ok := raw["timestamp"]; ok {
		var num int64
		if err := json.Unmarshal(rawVal, &num); err == nil {
			raw["timestamp"], _ = json.Marshal(strconv.FormatInt(num, 10))
		}
	}

	// Re-marshal to JSON with string values for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	if discardUnknown {
		opts := protojson.UnmarshalOptions{DiscardUnknown: true}
		return opts.Unmarshal(modified, x)
	}
	return protojson.Unmarshal(modified, x)
}
